### ISSUE TITLE
use xml_easy_child in for loop ?

### ISSUE THREAD

**Issue by ryzenX** [ooxi/xml.c#17]
Hello i want to use xml_easy in for lopp like this :

```
        struct xml_node* root = xml_document_root(document);
        size_t const number_of_features_type = xml_node_children(root);
        int i;
        for( i = 0; i < number_of_features_type; i++ ){
            
            struct xml_node* myxml_node = xml_easy_child(root, i, 0);
        }
```

but i have this error
```
warning: passing argument 2 of ‘xml_easy_child’ makes pointer from integer without a cast [enabled by default]
note: expected ‘const uint8_t *’ but argument is of type ‘unsigned char’
```

how "convert" my i variable to const ? or have you other solution ?

**Comment by ooxi** [comment]
Hi @ryzenX,


sorry for replying so late, the notification for this issue got swallowed by GitHub :-(

`xml_easy_child` enables you to access a child by name, thus expecting `uint8_t const*`. Since you want to loop over all children, you don't need an access by name, but by index (`i` in your case).

Try using `xml_node_child` instead:

```
size_t const number_of_features_type = xml_node_children(root);

int i; for(i = 0; i < number_of_features_type; i++){
    struct xml_node* child = xml_easy_child(root, i);
}
```


Kind regards

**Comment by ooxi** [comment]
I'll close this issue, since no further feedback was received. Feel free to reopen this task if you need help :-)
